name: Build 'Dark Souls Remastered read-only save' to exe

on:
  push:
    paths: 
      - 'darks-souls-readonly-save.ahk2'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'darks-souls-readonly-save.ahk2'
  workflow_dispatch:
  
permissions:
  packages: write
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ahk script to exe
        uses: nukdokplex/autohotkey-build@v1
        with: 
          version: v2.0.18
          in: darks-souls-readonly-save.ahk2
          x64_suffix: ''
          compression: upx
          
      - name: Release
        uses: actions/upload-artifact@master
        with:
          name: 'Dark Souls Remastered read-only save.exe'
          path: 'build\darks-souls-readonly-save.exe'

      - name: Publish release
        uses: ncipollo/release-action@v1
        with:
          name: Dark Souls Remastered read-only save ${{ github.sha }}
          tag: DarkSoulsReadOnlySave${{ github.sha }}
          draft: false
          artifacts: 'build\darks-souls-readonly-save.exe'
          
